# The services of the project.

# Each service listed is deployed
# to power your Platform.sh project.

db:
  type: postgresql:12
  disk: 256
# Uncomment the line below to use a MySQL database
# dbmysql:
#   type: oracle-mysql:8.0
#   disk: 256
